### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by RobGarciaLD** [gabe927/gma3-subfixture-layout#2]
Not all that familiar with navigating Github.  What's the best way to get this plugin from Github into MA3?

Thanks,

Rob

**Comment by gabe927** [comment]
You can do one of two ways:

1) Download the XML file from the releases page (https://github.com/gabe927/gma3-subfixture-layout/releases/) and import it into MA. Please refer to the MA manual pages on file management for how to import the XML. https://help2.malighting.com/Page/grandMA3/file_management/en/1.6

2) Copy the code in the main.lua file in the src folder and paste it directly into the plugin editor in MA.
