### ISSUE TITLE
LUA Runtime Error [ string "Subfix Layout Builder@main.lua" ] :80: attemp to get length of a nil value ( local 'l')

### ISSUE THREAD

**Issue by Voronenskii** [gabe927/gma3-subfixture-layout#3]
hello.Please help me.  The plugin doesn't work for me =( A layout builder for subfixtures in GrandMA3
my GrandMa 3 v1.8.8.2.

**Comment by gabe927** [comment]
Sounds like you're not selecting elements in the template layout. Make special care that you're selecting the elements while in **Setup** on the layout view since this will activate the "Selected" parameter for the element. Check step 2 in the README for more details.

**Comment by Voronenskii** [comment]
Thanks. The problem was in layout pool. Good Plugin, super.
